AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/hello
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  world:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/world
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /world
            Method: get
  find_user:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/find_user
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /find_user
            Method: post
  participate_group:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/participate_group
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /participate_group
            Method: post